# Generated by Django 5.2.17 on 2026-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(max_length=60, verbose_name='kind')),
                ('dedupe_key', models.CharField(max_length=200, verbose_name='dedupe key')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'E-mail'), ('log', 'Log')], default='log', max_length=10, verbose_name='channel')),
            ],
            options={
                'verbose_name': 'alert',
                'verbose_name_plural': 'alerts',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['dedupe_key', '-sent_at'], name='ops_alert_dedupe_idx')],
            },
        ),
    ]
