# Generated by Django 5.2.17 on 2026-09-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_search_vector_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewArticle',
            fields=[
            ],
            options={
                'verbose_name': 'review queue item',
                'verbose_name_plural': 'review queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.article',),
        ),
    ]
