# Generated by Django 5.2.17 on 2026-09-25 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_postgres_extensions'),
        ("institutions", "0001_institutions_programs_professions"),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_uz_cyrl', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('body_uz', models.TextField(blank=True, null=True, verbose_name='body')),
                ('body_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='body')),
                ('body_ru', models.TextField(blank=True, null=True, verbose_name='body')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='body')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='show in footer')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_title_uz', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_uz_cyrl', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=170, verbose_name='SEO description')),
                ('seo_description_uz', models.CharField(blank=True, max_length=170, null=True, verbose_name='SEO description')),
                ('seo_description_uz_cyrl', models.CharField(blank=True, max_length=170, null=True, verbose_name='SEO description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=170, null=True, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=170, null=True, verbose_name='SEO description')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ('order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('site_name', models.CharField(default='EDUCORE', max_length=100, verbose_name='site name')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='tagline')),
                ('tagline_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline')),
                ('tagline_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline')),
                ('tagline_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline')),
                ('tagline_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='tagline')),
                ('publish_mode', models.CharField(blank=True, choices=[('auto', 'Avtomatik'), ('review', 'Tahririyat koʻrigi'), ('off', 'Oʻchirilgan')], default='', max_length=10, verbose_name='publish mode')),
                ('publish_confidence_threshold', models.FloatField(blank=True, null=True, verbose_name='publish confidence threshold')),
                ('on_source_delete', models.CharField(blank=True, choices=[('archive', 'Arxivlash'), ('keep', 'Saqlab qolish')], default='', max_length=10, verbose_name='on source delete')),
                ('ai_daily_usd_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='AI daily budget (USD)')),
                ('ai_translate_to', models.JSONField(blank=True, null=True, verbose_name='AI translation languages')),
                ('live_panel_refresh_seconds', models.PositiveIntegerField(default=30, verbose_name='live panel refresh (s)')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact e-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='contact phone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('address_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('address_uz_cyrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('footer_text', models.TextField(blank=True, verbose_name='footer text')),
                ('footer_text_uz', models.TextField(blank=True, null=True, verbose_name='footer text')),
                ('footer_text_uz_cyrl', models.TextField(blank=True, null=True, verbose_name='footer text')),
                ('footer_text_ru', models.TextField(blank=True, null=True, verbose_name='footer text')),
                ('footer_text_en', models.TextField(blank=True, null=True, verbose_name='footer text')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('ga_measurement_id', models.CharField(blank=True, max_length=32, verbose_name='GA measurement id')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.CharField(max_length=300, verbose_name='question')),
                ('question_uz', models.CharField(max_length=300, null=True, verbose_name='question')),
                ('question_uz_cyrl', models.CharField(max_length=300, null=True, verbose_name='question')),
                ('question_ru', models.CharField(max_length=300, null=True, verbose_name='question')),
                ('question_en', models.CharField(max_length=300, null=True, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_uz', models.TextField(null=True, verbose_name='answer')),
                ('answer_uz_cyrl', models.TextField(null=True, verbose_name='answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='answer')),
                ('answer_en', models.TextField(null=True, verbose_name='answer')),
                ('topic', models.CharField(choices=[('qabul', 'Qabul'), ('talim', 'Taʼlim'), ('kursant', 'Kursantlar'), ('talaba', 'Talabalar'), ('kasb', 'Kasblar'), ('murojaat', 'Murojaat'), ('umumiy', 'Umumiy')], default='umumiy', max_length=20, verbose_name='topic')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='institutions.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('topic', 'order', 'pk'),
                'indexes': [models.Index(fields=['topic', 'is_published'], name='core_faq_topic_pub_idx')],
            },
        ),
    ]
