"""Seed data: programs (yoʻnalishlar), ≥ 4 per institution with varied levels, all `needs_verification=True`.

Official classifier codes are deliberately left blank — they must come from the institution (HA9), never guessed.
Tuple: (institution abbreviation, slug, name, level, form, duration_years, language, profession slugs).
"""

from __future__ import annotations

PROGRAMS: list[tuple[str, str, str, str, str, float | None, str, list[str]]] = [
    # FVV Akademiyasi
    (
        "FVV",
        "yongin-xavfsizligi",
        "Yongʻin xavfsizligi",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek, rus",
        ["yongin-xavfsizligi-muhandisi"],
    ),
    (
        "FVV",
        "favqulodda-vaziyatlarda-muhofaza",
        "Favqulodda vaziyatlarda aholi va hududlarni muhofaza qilish",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek",
        ["fuqaro-muhofazasi-mutaxassisi", "qutqaruvchi"],
    ),
    (
        "FVV",
        "texnosfera-xavfsizligi-magistratura",
        "Texnosfera xavfsizligi",
        "magistr",
        "kunduzgi",
        2,
        "oʻzbek",
        ["ekologik-nazorat-inspektori"],
    ),
    (
        "FVV",
        "qutqaruv-ishlari-qayta-tayyorlash",
        "Qidiruv-qutqaruv ishlari",
        "qayta_tayyorlash",
        "kunduzgi",
        0.5,
        "oʻzbek",
        ["qutqaruvchi", "favqulodda-vaziyatlar-dispetcheri"],
    ),
    (
        "FVV",
        "rahbar-kadrlar-malaka-oshirish",
        "Rahbar kadrlar malakasini oshirish",
        "malaka_oshirish",
        "aralash",
        None,
        "oʻzbek",
        ["fuqaro-muhofazasi-mutaxassisi"],
    ),
    # IIV Akademiyasi
    (
        "IIV",
        "huquqshunoslik-ichki-ishlar",
        "Huquqshunoslik (ichki ishlar faoliyati)",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek, rus",
        ["tergovchi", "profilaktika-inspektori", "huquqshunos"],
    ),
    (
        "IIV",
        "tezkor-qidiruv-faoliyati",
        "Tezkor-qidiruv faoliyati",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek",
        ["tezkor-qidiruv-xodimi"],
    ),
    (
        "IIV",
        "kriminalistika-ekspertiza",
        "Sud ekspertizasi",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek",
        ["kriminalist-ekspert", "sudmed-ekspert-yordamchisi"],
    ),
    (
        "IIV",
        "kiberxavfsizlik-ichki-ishlar",
        "Kiberjinoyatlarga qarshi kurashish",
        "magistr",
        "kunduzgi",
        2,
        "oʻzbek",
        ["kiberxavfsizlik-mutaxassisi", "it-forensika-mutaxassisi"],
    ),
    ("IIV", "ichki-ishlar-doktorantura", "Yuridik fanlar", "doktorantura", "kunduzgi", 3, "oʻzbek, rus", []),
    # Bojxona instituti
    ("DBQ", "bojxona-ishi", "Bojxona ishi", "bakalavr", "kunduzgi", 4, "oʻzbek, rus", ["bojxona-inspektori"]),
    ("DBQ", "bojxona-huquqi", "Bojxona huquqi", "bakalavr", "kunduzgi", 4, "oʻzbek", ["huquqshunos"]),
    (
        "DBQ",
        "bojxona-ishi-magistratura",
        "Bojxona ishini tashkil etish va boshqarish",
        "magistr",
        "kunduzgi",
        2,
        "oʻzbek",
        ["bojxona-inspektori"],
    ),
    (
        "DBQ",
        "kinologiya-kurs",
        "Bojxona kinologiyasi",
        "kurs",
        "kunduzgi",
        0.5,
        "oʻzbek",
        ["bojxona-kinologi"],
    ),
    (
        "DBQ",
        "bojxona-xodimlari-malaka-oshirish",
        "Bojxona xodimlari malakasini oshirish",
        "malaka_oshirish",
        "masofaviy",
        None,
        "oʻzbek, rus",
        ["bojxona-inspektori"],
    ),
    # Huquqni muhofaza qilish akademiyasi
    (
        "HMQA",
        "huquqni-muhofaza-qilish-faoliyati-magistratura",
        "Huquqni muhofaza qilish faoliyati",
        "magistr",
        "kunduzgi",
        2,
        "oʻzbek, rus, ingliz",
        ["prokuror-yordamchisi", "tergovchi"],
    ),
    (
        "HMQA",
        "prokurorlik-nazorati",
        "Prokurorlik nazorati",
        "magistr",
        "sirtqi",
        2.5,
        "oʻzbek",
        ["prokuror-yordamchisi"],
    ),
    (
        "HMQA",
        "raqamli-kriminalistika",
        "Raqamli kriminalistika",
        "malaka_oshirish",
        "aralash",
        None,
        "oʻzbek",
        ["it-forensika-mutaxassisi", "kiberxavfsizlik-mutaxassisi"],
    ),
    (
        "HMQA",
        "prokuratura-xodimlari-qayta-tayyorlash",
        "Prokuratura xodimlarini qayta tayyorlash",
        "qayta_tayyorlash",
        "kunduzgi",
        0.5,
        "oʻzbek",
        ["prokuror-yordamchisi", "huquqshunos"],
    ),
    (
        "HMQA",
        "huquqshunoslik-doktorantura",
        "Yuridik fanlar (huquqni muhofaza qilish)",
        "doktorantura",
        "kunduzgi",
        3,
        "oʻzbek, rus",
        [],
    ),
    # Jamoat xavfsizligi universiteti
    (
        "JXU",
        "jamoat-xavfsizligi",
        "Jamoat xavfsizligini taʼminlash",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek",
        ["jamoat-xavfsizligi-inspektori", "patrul-post-xizmati-xodimi"],
    ),
    (
        "JXU",
        "harbiy-boshqaruv",
        "Qoʻshinlarni boshqarish (Milliy gvardiya)",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek",
        ["jamoat-xavfsizligi-inspektori"],
    ),
    (
        "JXU",
        "psixologiya-xizmat-faoliyati",
        "Xizmat faoliyati psixologiyasi",
        "bakalavr",
        "kunduzgi",
        4,
        "oʻzbek",
        ["psixolog"],
    ),
    (
        "JXU",
        "jamoat-xavfsizligi-magistratura",
        "Jamoat xavfsizligi va huquqbuzarliklar profilaktikasi",
        "magistr",
        "kunduzgi",
        2,
        "oʻzbek",
        ["profilaktika-inspektori"],
    ),
    (
        "JXU",
        "ofitserlar-malaka-oshirish",
        "Ofitserlar malakasini oshirish",
        "malaka_oshirish",
        "kunduzgi",
        None,
        "oʻzbek",
        ["jamoat-xavfsizligi-inspektori"],
    ),
]

LEVEL_REQUIREMENTS: dict[str, str] = {
    "bakalavr": "Umumiy oʻrta, oʻrta maxsus yoki professional taʼlim toʻgʻrisidagi hujjat; tibbiy koʻrik, "
    "jismoniy tayyorgarlik sinovi va test sinovlaridan muvaffaqiyatli oʻtish.",
    "magistr": "Bakalavr diplomi, kasbiy tajriba (talab qilingan hollarda) va mutaxassislik fanidan kirish sinovi.",
    "doktorantura": "Magistr darajasi, ilmiy ishlar roʻyxati va ilmiy rahbar tavsiyanomasi.",
    "kurs": "Tegishli bojxona organi yoki idoraning yoʻllanmasi.",
    "qayta_tayyorlash": "Oliy maʼlumot va tegishli idoraning yoʻllanmasi.",
    "malaka_oshirish": "Amaldagi xodim maqomi va idora yoʻllanmasi.",
}

LEVEL_QUALIFICATION: dict[str, str] = {
    "bakalavr": "Bakalavr",
    "magistr": "Magistr",
    "doktorantura": "Falsafa doktori (PhD)",
    "kurs": "Sertifikat",
    "qayta_tayyorlash": "Qayta tayyorlash toʻgʻrisida diplom",
    "malaka_oshirish": "Malaka oshirish toʻgʻrisida guvohnoma",
}
