"""Download self-hosted subset variable fonts into `static/fonts/` and write `assets/css/fonts.css`.

Subsets: latin, latin-ext (covers ʻ U+02BB / ʼ U+02BC used in Uzbek Latin), cyrillic, cyrillic-ext.
The browser downloads only the subsets a page actually uses (`unicode-range`). Run via `make fonts`.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "static" / "fonts"
CSS_OUT = ROOT / "assets" / "css" / "fonts.css"
CDN = "https://cdn.jsdelivr.net/npm"
SUBSETS = ("latin", "latin-ext", "cyrillic", "cyrillic-ext")

# (npm package, pinned major, css file, family name used in the design tokens)
FAMILIES = (
    ("@fontsource-variable/manrope", "5", "wght.css", "Manrope Variable"),
    ("@fontsource-variable/source-serif-4", "5", "wght.css", "Source Serif 4 Variable"),
    ("@fontsource-variable/jetbrains-mono", "5", "wght.css", "JetBrains Mono Variable"),
)

FACE_RE = re.compile(r"@font-face\s*\{(?P<body>[^}]*)\}", re.S)
URL_RE = re.compile(r"url\(\./files/(?P<file>[^)]+\.woff2)\)")


def subset_of(filename: str) -> str | None:
    """Return the wanted subset encoded in a Fontsource file name (upright only), else None."""
    for subset in sorted(SUBSETS, key=len, reverse=True):
        if filename.endswith(f"-{subset}-wght-normal.woff2"):
            return subset
    return None


def fetch_family(client: httpx.Client, package: str, major: str, css_name: str) -> list[str]:
    """Download one family's wanted subsets and return rewritten @font-face blocks."""
    base = f"{CDN}/{package}@{major}"
    css = client.get(f"{base}/{css_name}").raise_for_status().text
    blocks: list[str] = []
    for match in FACE_RE.finditer(css):
        body = match.group("body")
        url = URL_RE.search(body)
        if not url:
            continue
        filename = url.group("file")
        subset = subset_of(filename)
        if subset is None:
            continue
        target = FONT_DIR / filename
        if not target.exists():
            target.write_bytes(client.get(f"{base}/files/{filename}").raise_for_status().content)
            print(f"  downloaded {filename} ({target.stat().st_size // 1024} KB)")
        body = re.sub(r"src:[^;]*;", f"src: url(../fonts/{filename}) format('woff2-variations');", body)
        body = re.sub(r"font-display:[^;]*;", "font-display: swap;", body)
        blocks.append(f"/* {package} — {subset} */\n@font-face {{{body.rstrip()}\n}}")
    return blocks


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    blocks: list[str] = []
    with httpx.Client(timeout=60, follow_redirects=True) as client:
        for package, major, css_name, family in FAMILIES:
            print(f"{family}:")
            family_blocks = fetch_family(client, package, major, css_name)
            if not family_blocks:
                print(f"  no @font-face blocks found for {package}", file=sys.stderr)
                return 1
            blocks.extend(family_blocks)
    header = "/* Generated by scripts/fetch_fonts.py — do not edit by hand. */\n"
    CSS_OUT.write_text(header + "\n\n".join(blocks) + "\n", encoding="utf-8")
    print(f"wrote {CSS_OUT.relative_to(ROOT)} with {len(blocks)} @font-face rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
