# Generated by Django 5.2.17 on 2026-09-25 07:48

import pgvector.django.vector
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_postgres_extensions"),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBudgetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('usd_spent', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10, verbose_name='spent (USD)')),
                ('input_tokens', models.PositiveBigIntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.PositiveBigIntegerField(default=0, verbose_name='output tokens')),
                ('runs', models.PositiveIntegerField(default=0, verbose_name='runs')),
                ('is_exhausted', models.BooleanField(default=False, verbose_name='exhausted')),
            ],
            options={
                'verbose_name': 'AI budget day',
                'verbose_name_plural': 'AI budget days',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stage', models.CharField(choices=[('triage', 'triage'), ('normalize', 'normalize'), ('extract', 'extract'), ('embed', 'embed'), ('dedupe', 'dedupe'), ('generate', 'generate'), ('fact_guard', 'fact_guard'), ('media_select', 'media_select'), ('structured_upsert', 'structured_upsert'), ('publish_policy', 'publish_policy'), ('post_publish', 'post_publish'), ('translate', 'translate'), ('regenerate', 'regenerate'), ('digest', 'digest')], max_length=20, verbose_name='stage')),
                ('provider', models.CharField(choices=[('anthropic', 'anthropic'), ('mock', 'mock'), ('rules', 'rules'), ('local', 'local')], max_length=10, verbose_name='provider')),
                ('model', models.CharField(blank=True, max_length=80, verbose_name='model')),
                ('prompt_version', models.CharField(blank=True, max_length=20, verbose_name='prompt version')),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='input hash')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='input tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='output tokens')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10, verbose_name='cost (USD)')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='duration (ms)')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Xato'), ('skipped', 'Oʻtkazildi'), ('cached', 'Keshdan')], max_length=10, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('request_id', models.CharField(blank=True, max_length=100, verbose_name='request id')),
                ('output', models.JSONField(blank=True, null=True, verbose_name='output')),
            ],
            options={
                'verbose_name': 'AI run',
                'verbose_name_plural': 'AI runs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('first_seen_at', models.DateTimeField(verbose_name='first seen')),
                ('last_seen_at', models.DateTimeField(verbose_name='last seen')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='embedding')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='posts')),
                ('sources_count', models.PositiveIntegerField(default=0, verbose_name='sources')),
            ],
            options={
                'verbose_name': 'event cluster',
                'verbose_name_plural': 'event clusters',
                'ordering': ('-last_seen_at',),
            },
        ),
    ]
