# Generated by Django 5.2.17 on 2026-09-25 07:48

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_runs_budget_clusters"),
        ("content", "0001_articles_events_admissions_stories"),
        ("telegram", "0001_sources_posts_media_outbox"),
    ]

    operations = [
        migrations.AddField(
            model_name='airun',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='content.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='airun',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='telegram.telegrampost', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='eventcluster',
            name='canonical_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.article', verbose_name='canonical article'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['post', 'stage'], name='ai_run_post_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['created_at'], name='ai_run_created_idx'),
        ),
        migrations.AddIndex(
            model_name='airun',
            index=models.Index(fields=['stage', 'input_hash', 'prompt_version'], name='ai_run_cache_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcluster',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ai_cluster_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
