# Generated by Django 5.2.17 on 2026-09-25 07:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_postgres_extensions"),
        ("ai", "0001_runs_budget_clusters"),
        ("institutions", "0001_institutions_programs_professions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('username', models.CharField(help_text='Without @, lowercase.', max_length=64, unique=True, verbose_name='username')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('about_text', models.TextField(blank=True, verbose_name='about')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='telegram/sources/', verbose_name='photo')),
                ('telegram_channel_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='channel id')),
                ('access_hash', models.BigIntegerField(blank=True, null=True, verbose_name='access hash')),
                ('ingest_method', models.CharField(choices=[('mtproto', 'MTProto (user session)'), ('bot', 'Bot API (reserved)')], default='mtproto', max_length=10, verbose_name='ingest method')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('live', 'Jonli'), ('degraded', 'Nosoz'), ('offline', 'Oflayn'), ('disabled', 'Oʻchirilgan')], db_index=True, default='offline', max_length=10, verbose_name='status')),
                ('last_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='last message id')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='last message at')),
                ('last_update_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='last update seen at')),
                ('last_gapcheck_at', models.DateTimeField(blank=True, null=True, verbose_name='last gap check at')),
                ('backfill_done_at', models.DateTimeField(blank=True, null=True, verbose_name='backfill done at')),
                ('subscribers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='subscribers')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='error count')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='joined at')),
                ('signature_patterns', models.JSONField(blank=True, default=list, help_text='Regexes stripped from post text before AI.', verbose_name='signature patterns')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sources', to='institutions.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'Telegram source',
                'verbose_name_plural': 'Telegram sources',
                'ordering': ('institution__order', 'username'),
            },
        ),
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('telegram_message_id', models.BigIntegerField(verbose_name='message id')),
                ('grouped_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='album id')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('entities', models.JSONField(blank=True, default=list, verbose_name='entities')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='links')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='hashtags')),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('telegram_url', models.URLField(blank=True, max_length=300, verbose_name='Telegram URL')),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='content hash')),
                ('has_media', models.BooleanField(default=False, verbose_name='has media')),
                ('media_count', models.PositiveSmallIntegerField(default=0, verbose_name='media count')),
                ('views', models.PositiveIntegerField(blank=True, null=True, verbose_name='views')),
                ('forwards', models.PositiveIntegerField(blank=True, null=True, verbose_name='forwards')),
                ('reactions', models.JSONField(blank=True, default=dict, verbose_name='reactions')),
                ('reply_to_id', models.BigIntegerField(blank=True, null=True, verbose_name='reply to')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='forwarded')),
                ('forward_from', models.CharField(blank=True, max_length=255, verbose_name='forwarded from')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('is_backfill', models.BooleanField(default=False, verbose_name='from backfill')),
                ('raw_json', models.JSONField(blank=True, default=dict, verbose_name='raw message')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='language')),
                ('processing_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('queued', 'Navbatda'), ('processing', 'Qayta ishlanmoqda'), ('processed', 'Qayta ishlandi'), ('skipped', 'Oʻtkazib yuborildi'), ('failed', 'Xato')], default='pending', max_length=12, verbose_name='processing status')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('skip_reason', models.CharField(blank=True, max_length=40, verbose_name='skip reason')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True, verbose_name='embedding')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('importance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='importance')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='ai.eventcluster', verbose_name='cluster')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='telegram.telegramsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'Telegram post',
                'verbose_name_plural': 'Telegram posts',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='IngestionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('backfill', 'Backfill'), ('gapcheck', 'Gap check'), ('refresh_engagement', 'Engagement refresh'), ('resolve_source', 'Resolve source'), ('retry_media', 'Retry media')], max_length=20, verbose_name='kind')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='parameters')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Bajarilmoqda'), ('done', 'Bajarildi'), ('failed', 'Xato')], default='pending', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='result')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('source', models.ForeignKey(blank=True, help_text='Empty = all active sources.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='telegram.telegramsource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'ingestion request',
                'verbose_name_plural': 'ingestion requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TelegramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('telegram_message_id', models.BigIntegerField(db_index=True, verbose_name='message id')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('kind', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video'), ('document', 'Hujjat'), ('audio', 'Audio'), ('voice', 'Ovozli xabar'), ('animation', 'Animatsiya'), ('sticker', 'Stiker'), ('webpage', 'Veb sahifa'), ('other', 'Boshqa')], max_length=12, verbose_name='kind')),
                ('telegram_file_id', models.BigIntegerField(blank=True, null=True, verbose_name='file id')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='size (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (s)')),
                ('original', models.FileField(blank=True, max_length=300, upload_to='', verbose_name='original')),
                ('derivatives', models.JSONField(blank=True, default=dict, verbose_name='derivatives')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('downloaded', 'Yuklandi'), ('ready', 'Tayyor'), ('failed', 'Xato')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='telegram.telegrampost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'Telegram media',
                'verbose_name_plural': 'Telegram media',
                'ordering': ('post', 'order'),
                'constraints': [models.UniqueConstraint(fields=('post', 'telegram_message_id'), name='uniq_media_post_message')],
            },
        ),
        migrations.CreateModel(
            name='IngestionOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('telegram.post.created', 'telegram.post.created'), ('telegram.post.edited', 'telegram.post.edited'), ('telegram.post.deleted', 'telegram.post.deleted')], max_length=32, verbose_name='event type')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='payload hash')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='locked until')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='terminal failures')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('is_dead', models.BooleanField(db_index=True, default=False, verbose_name='dead')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='telegram.telegrampost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'outbox event',
                'verbose_name_plural': 'outbox events',
                'ordering': ('created_at',),
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['created_at'], name='tg_outbox_unprocessed_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'event_type', 'payload_hash'), name='uniq_outbox_post_event_hash')],
            },
        ),
        migrations.AddIndex(
            model_name='telegrampost',
            index=models.Index(fields=['source', '-published_at'], name='tg_post_source_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrampost',
            index=models.Index(fields=['-published_at'], name='tg_post_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrampost',
            index=models.Index(fields=['processing_status'], name='tg_post_status_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrampost',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tg_post_search_gin'),
        ),
        migrations.AddIndex(
            model_name='telegrampost',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='tg_post_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='telegrampost',
            constraint=models.UniqueConstraint(fields=('source', 'telegram_message_id'), name='uniq_post_source_message'),
        ),
        migrations.AddConstraint(
            model_name='telegrampost',
            constraint=models.UniqueConstraint(condition=models.Q(('grouped_id__isnull', False)), fields=('source', 'grouped_id'), name='uniq_post_source_album'),
        ),
        migrations.AddIndex(
            model_name='ingestionrequest',
            index=models.Index(fields=['status', 'created_at'], name='tg_request_status_idx'),
        ),
    ]
