# Generated by Django 5.2.17 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_post_search_vector_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='missing_checks',
            field=models.PositiveSmallIntegerField(default=0, help_text='Deleted after two consecutive misses.', verbose_name='consecutive gap-check misses'),
        ),
    ]
