# Generated by Django 5.2.17 on 2026-09-25 07:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_institutions_programs_professions"),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(unique=True, verbose_name='date')),
                ('posts_ingested', models.PositiveIntegerField(default=0, verbose_name='posts ingested')),
                ('articles_published', models.PositiveIntegerField(default=0, verbose_name='articles published')),
                ('articles_review', models.PositiveIntegerField(default=0, verbose_name='articles sent to review')),
                ('ai_runs', models.PositiveIntegerField(default=0, verbose_name='AI runs')),
                ('ai_cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10, verbose_name='AI cost (USD)')),
                ('appeals_new', models.PositiveIntegerField(default=0, verbose_name='new appeals')),
                ('pageviews', models.PositiveIntegerField(default=0, verbose_name='page views')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='unique visitors')),
                ('search_queries', models.PositiveIntegerField(default=0, verbose_name='search queries')),
            ],
            options={
                'verbose_name': 'daily statistic',
                'verbose_name_plural': 'daily statistics',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('query_norm', models.CharField(max_length=200, unique=True, verbose_name='normalized query')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='count')),
                ('last_searched_at', models.DateTimeField(db_index=True, verbose_name='last searched at')),
            ],
            options={
                'verbose_name': 'search query',
                'verbose_name_plural': 'search queries',
                'ordering': ('-count',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('posts', models.PositiveIntegerField(default=0, verbose_name='posts')),
                ('articles', models.PositiveIntegerField(default=0, verbose_name='articles')),
                ('tg_views_sum', models.PositiveBigIntegerField(default=0, verbose_name='Telegram views')),
                ('tg_forwards_sum', models.PositiveBigIntegerField(default=0, verbose_name='Telegram forwards')),
                ('by_category', models.JSONField(blank=True, default=dict, verbose_name='by category')),
                ('by_content_type', models.JSONField(blank=True, default=dict, verbose_name='by content type')),
                ('by_hour', models.JSONField(blank=True, default=list, verbose_name='by hour')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='institutions.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'institution daily statistic',
                'verbose_name_plural': 'institution daily statistics',
                'ordering': ('-date', 'institution__order'),
                'indexes': [models.Index(fields=['institution', 'date'], name='analytics_inst_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'institution'), name='uniq_inst_daily_stat')],
            },
        ),
    ]
