# Generated by Django 5.2.17 on 2026-09-25 07:48

import apps.appeals.models
import django.core.files.storage
import django.db.models.deletion
import pathlib
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_institutions_programs_professions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tracking_code', models.CharField(max_length=20, unique=True, verbose_name='tracking code')),
                ('topic', models.CharField(choices=[('qabul', 'Qabul'), ('talim', 'Taʼlim jarayoni'), ('kursant_talaba', 'Kursant va talabalar'), ('shikoyat', 'Shikoyat'), ('taklif', 'Taklif'), ('hamkorlik', 'Hamkorlik'), ('boshqa', 'Boshqa')], max_length=16, verbose_name='topic')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='message')),
                ('consent', models.BooleanField(default=False, verbose_name='consent to data processing')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Koʻrib chiqilmoqda'), ('answered', 'Javob berildi'), ('closed', 'Yopilgan'), ('rejected', 'Rad etilgan')], db_index=True, default='new', max_length=12, verbose_name='status')),
                ('priority', models.CharField(choices=[('normal', 'Oddiy'), ('high', 'Yuqori')], default='normal', max_length=8, verbose_name='priority')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP hash')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
                ('locale', models.CharField(default='uz', max_length=10, verbose_name='language')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('internal_note', models.TextField(blank=True, verbose_name='internal note')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='institutions.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'appeal',
                'verbose_name_plural': 'appeals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppealAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/data/private')), upload_to=apps.appeals.models.attachment_upload_to, verbose_name='file')),
                ('original_name', models.CharField(max_length=255, verbose_name='original name')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='size (bytes)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='appeals.appeal', verbose_name='appeal')),
            ],
            options={
                'verbose_name': 'appeal attachment',
                'verbose_name_plural': 'appeal attachments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppealMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('body', models.TextField(verbose_name='text')),
                ('is_public', models.BooleanField(default=True, verbose_name='visible to applicant')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notified at')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='appeals.appeal', verbose_name='appeal')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'appeal message',
                'verbose_name_plural': 'appeal messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalAppeal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, verbose_name='tracking code')),
                ('topic', models.CharField(choices=[('qabul', 'Qabul'), ('talim', 'Taʼlim jarayoni'), ('kursant_talaba', 'Kursant va talabalar'), ('shikoyat', 'Shikoyat'), ('taklif', 'Taklif'), ('hamkorlik', 'Hamkorlik'), ('boshqa', 'Boshqa')], max_length=16, verbose_name='topic')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='message')),
                ('consent', models.BooleanField(default=False, verbose_name='consent to data processing')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Koʻrib chiqilmoqda'), ('answered', 'Javob berildi'), ('closed', 'Yopilgan'), ('rejected', 'Rad etilgan')], db_index=True, default='new', max_length=12, verbose_name='status')),
                ('priority', models.CharField(choices=[('normal', 'Oddiy'), ('high', 'Yuqori')], default='normal', max_length=8, verbose_name='priority')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='IP hash')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='user agent')),
                ('locale', models.CharField(default='uz', max_length=10, verbose_name='language')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('internal_note', models.TextField(blank=True, verbose_name='internal note')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institutions.institution', verbose_name='institution')),
            ],
            options={
                'verbose_name': 'historical appeal',
                'verbose_name_plural': 'historical appeals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='appeal',
            index=models.Index(fields=['status', 'created_at'], name='appeal_status_created_idx'),
        ),
    ]
