# Generated by Django 5.2.17 on 2026-09-25 11:12

import apps.appeals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0001_appeals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealattachment',
            name='file',
            field=models.FileField(max_length=200, storage=apps.appeals.models.get_private_storage, upload_to=apps.appeals.models.attachment_upload_to, verbose_name='file'),
        ),
    ]
