# Generated by Django 5.2.17 on 2026-09-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0002_attachment_callable_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonymized at'),
        ),
        migrations.AddField(
            model_name='historicalappeal',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anonymized at'),
        ),
    ]
